export const UPDATE_REQUIRED_STATUS_QUESTION =
  "UPDATE_REQUIRED_STATUS_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_QUESTION_TYPE = "UPDATE_QUESTION_TYPE";
export const UPDATE_QUESTION_OPTIONS = "UPDATE_QUESTION_OPTIONS";
export const UPDATE_MULTIPLE_OPTIONS_SELECT_STATUS =
  "UPDATE_MULTIPLE_OPTIONS_SELECT_STATUS";
export const UPDATE_SHOW_EDIT_QUESTION = "UPDATE_SHOW_EDIT_QUESTION";
export const ADD_NEW_QUESTION = "ADD_NEW_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const HIDE_ALL_EDIT_QUESTION = "HIDE_ALL_EDIT_QUESTION";
export const RESET_ALL = "RESET_ALL";
