export const ALL_GIG_REQUEST = "ALL_GIG_REQUEST";
export const ALL_GIG_SUCCESS = "ALL_GIG_SUCCESS";
export const ALL_GIG_FAIL = "ALL_GIG_FAIL";

export const USER_GIGS_REQUEST = "USER_GIGS_REQUEST";
export const USER_GIGS_SUCCESS = "USER_GIGS_SUCCESS";
export const USER_GIGS_FAIL = "USER_GIGS_FAIL";

export const GIG_DETAIL_REQUEST = "GIG_DETAIL_REQUEST";
export const GIG_DETAIL_SUCCESS = "GIG_DETAIL_SUCCESS";
export const GIG_DETAIL_FAIL = "GIG_DETAIL_FAIL";
export const UPDATE_GIG_DETAIL_SUCCESS = "UPDATE_GIG_DETAIL_SUCCESS";
export const GIG_DETAIL_RESET = "GIG_DETAIL_RESET";

export const UPDATE_ALL_GIGS_REQUEST = "UPDATE_ALL_GIGS_REQUEST";
export const UPDATE_ALL_GIGS_SUCCESS = "UPDATE_ALL_GIGS_SUCCESS";
export const UPDATE_ALL_GIGS_FAIL = "UPDATE_ALL_GIGS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
