export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST";
export const ALL_ORDER_SUCCESS = "ALL_ORDER_SUCCESS";
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL";

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const UPDATE_ORDER_DETAIL_REQUEST = "UPDATE_ORDER_DETAIL_REQUEST";
export const UPDATE_ORDER_DETAIL_SUCCESS = "UPDATE_ORDER_DETAIL_SUCCESS";
export const UPDATE_ORDER_DETAIL_FAIL = "UPDATE_ORDER_DETAIL_FAIL";

export const UPDATE_ALL_ORDERS_REQUEST = "UPDATE_ALL_ORDERS_REQUEST";
export const UPDATE_ALL_ORDERS_SUCCESS = "UPDATE_ALL_ORDERS_SUCCESS";
export const UPDATE_ALL_ORDERS_FAIL = "UPDATE_ALL_ORDERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
