export const USER_REQUEST="USER_REQUEST"
export const USER_SUCCESS="USER_SUCCESS"
export const USER_FAIL="USER_FAIL"


export const GIG_USER_REQUEST="GIG_USER_REQUEST"
export const GIG_USER_SUCCESS="GIG_USER_SUCCESS"
export const GIG_USER_FAIL="GIG_USER_FAIL"