export const categoriesData = [
  "Graphics & design",
  "digital marketing",
  "Writing & Translation",
  "Video & Animation",
  "Music & Audio",
  "Programming & Tech",
  "Business",
  "Lifestyle",
  "Photography",
];

export const subCategoriesData = {
  "Graphics & design": [
    "Logo design",
    "Poster design",
    "Banner design",
    "Business card design",
    "Social media design",
    "Illustration",
    "T-shirt design",
    "Book cover design",
    "Packaging design",
    "Other design",
  ],
  "digital marketing": [
    "Social media marketing",
    "Search engine optimization",
    "Email marketing",
    "Content marketing",
    "Influencer marketing",
    "Marketing strategy",
    "Marketing consulting",
    "Other marketing",
  ],
  "Writing & Translation": [
    "Article & blog writing",
    "Resume writing",
    "Proofreading & editing",
    "Translation",
    "Copywriting",
    "Technical writing",
    "Other writing",
  ],
  "Video & Animation": [
    "Video editing",
    "Video production",
    "Video marketing",
    "Animation",
    "Whiteboard & Explainer videos",
    "Lyric & music videos",
    "Other video & animation",
  ],
  "Music & Audio": [
    "Voice over",
    "Songwriting",
    "Music production",
    "Mixing & mastering",
    "Sound effects",
    "Audio editing",
    "Other music & audio",
  ],
  "Programming & Tech": [
    "Web programming",
    "Mobile apps & web",
    "Game development",
    "Software testing",
    "Data analysis & reports",
    "Databases",
    "Support & IT",
    "Other programming & tech",
  ],
  Business: [
    "Virtual assistant",
    "Market research",
    "Presentations",
    "Financial analysis",
    "Business plans",
    "Branding services",
    "Legal consulting",
    "Other business",
  ],
  Lifestyle: [
    "Arts & crafts",
    "Beauty",
    "Relationship advice",
    "Spiritual & healing",
    "Astrology & tarot",
    "Health & fitness",
    "Dieting & weight loss",
    "Other lifestyle",
  ],
  Photography: [
    "Product photography",
    "Wedding photography",
    "Event photography",
    "Real estate photography",
    "Architecture photography",
    "Food photography",
    "Other photography",
  ],
};

export const tagsData = [
  "logo design",
  "graphic design",
  "illustration",
  "poster design",
  "business card design",
  "banner design",
  "social media design",
  "t-shirt design",
  "book cover design",
  "packaging design",
  "other design",
  "social media marketing",
  "search engine optimization",
  "email marketing",
  "content marketing",
  "influencer marketing",
  "marketing strategy",
  "marketing consulting",
  "other marketing",
  "article & blog writing",
  "resume writing",
  "proofreading & editing",
  "translation",
  "copywriting",
  "technical writing",
  "other writing",
  "video editing",
  "video production",
  "video marketing",
  "animation",
  "whiteboard & explainer videos",
  "lyric & music videos",
  "other video & animation",
  "voice over",
  "songwriting",
  "music production",
  "mixing & mastering",
  "sound effects",
  "audio editing",
  "other music & audio",
  "web programming",
  "mobile apps & web",
  "game development",
  "software testing",
  "data analysis & reports",
  "databases",
  "support & it",
  "other programming & tech",
  "virtual assistant",
  "market research",
  "presentations",
  "financial analysis",
  "business plans",
  "branding services",
  "legal consulting",
  "other business",
  "arts & crafts",
  "beauty",
  "relationship advice",
  "spiritual & healing",
  "astrology & tarot",
  "health & fitness",
  "dieting & weight loss",
  "other lifestyle",
  "product photography",
  "wedding photography",
  "event photography",
  "real estate photography",
  "architecture photography",
  "food photography",
  "other photography",
];

export const packagesData = ["Basic", "Standard", "Premium"];

export const deliveryTimeData = [
  "1 day delivery",
  "2 days delivery",
  "3 days delivery",
  "5 days delivery",
  "7 days delivery",
  "15 days delivery",
  "30 days delivery",
  "45 days delivery",
  "60 days delivery",
  "75 days delivery",
  "90 days delivery",
];

export const revisionsData = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "Unlimited",
];

export const questionTypeData = ["Free Text", "Multiple Choice"];
