// export const tagOptions = [
//   "web development",
//   "graphic design",
//   "content writing",
//   "mobile app development",
//   "ui/ux design",
//   "seo optimization",
//   "social media management",
//   "video editing",
//   "illustration",
//   "data entry",
//   "e-commerce development",
//   "copywriting",
//   "logo design",
//   "blogging",
//   "wordpress development",
//   "animation",
//   "virtual assistance",
//   "digital marketing",
//   "voiceover",
//   "email marketing",
//   "photography",
//   "transcription",
//   "app store optimization",
//   "proofreading",
//   "game development",
//   "infographic design",
//   "social media advertising",
//   "shopify development",
//   "bookkeeping",
//   "podcast editing",
//   "whiteboard animation",
//   "3d modeling",
//   "presentation design",
//   "e-book writing",
//   "data analysis",
//   "branding",
//   "resume writing",
//   "illustration",
//   "influencer marketing",
//   "product photography",
//   "landing page design",
//   "market research",
//   "voice acting",
//   "motion graphics",
//   "wordpress customization",
//   "content strategy",
//   "social media consulting",
//   "logo animation",
//   "data mining",
//   "android app development",
//   "web scraping",
//   "affiliate marketing",
//   "app ui design",
//   "video production",
//   "article writing",
//   "seo audit",
//   "character design",
//   "virtual events management",
//   "social media graphics",
//   "shopify setup",
//   "financial planning",
//   "podcast scriptwriting",
//   "explainer videos",
//   "architectural rendering",
//   "newsletter design",
//   "ghostwriting",
//   "social media marketing",
//   "app store review management",
//   "book cover design",
//   "voice assistant development",
//   "market analysis",
//   "scriptwriting",
//   "influencer outreach",
//   "data visualization",
//   "website optimization",
//   "facebook ads",
//   "portrait photography",
//   "animation scriptwriting",
//   "wordpress troubleshooting",
//   "business card design",
//   "social media content creation",
//   "logo redesign",
//   "market trend analysis",
//   "proof of concept (poc) development",
//   "seo copywriting",
//   "motion design",
//   "product design",
//   "catalog design",
//   "financial modeling",
//   "podcast hosting",
//   "explainer video scriptwriting",
//   "cad design",
//   "brochure design",
//   "business plan writing",
//   "social media growth strategy",
//   "wordpress migration",
//   "affiliate program management",
//   "user flow design",
//   "videography",
//   "data entry and analysis",
//   "app design",
//   "business writing",
//   "front-end development",
//   "logo redesign",
//   "video scriptwriting",
//   "social media strategy",
//   "mobile game development",
//   "creative writing",
//   "app marketing",
//   "digital illustration",
//   "user interface (ui) design",
//   "technical writing",
//   "backend development",
//   "poster design",
//   "ebook formatting",
//   "motion graphics animation",
//   "google ads campaigns",
//   "book editing",
//   "podcast cover design",
//   "app store optimization (aso)",
//   "software testing",
//   "package design",
//   "resume design",
//   "sound editing",
//   "email template design",
//   "data cleaning",
//   "facebook marketing",
//   "product rendering",
//   "business consulting",
//   "e-commerce management",
//   "whiteboard animation",
//   "book illustration",
//   "social media analytics",
//   "android app ui design",
//   "speech writing",
//   "api integration",
//   "event photography",
//   "logo animation",
//   "data visualization",
//   "landing page optimization",
//   "press release writing",
//   "video editing training",
//   "ui/ux consultation",
//   "ios app development",
//   "book formatting",
//   "explainer video production",
//   "youtube seo",
//   "financial analysis",
//   "presentation design",
//   "virtual reality (vr) development",
//   "resume writing",
//   "voice over scriptwriting",
//   "plugin development",
//   "catalog design",
//   "social media management training",
//   "app prototyping",
//   "market research report writing",
//   "blog management",
//   "online course creation",
//   "motion graphics design",
//   "youtube channel growth",
//   "wordpress theme customization",
//   "data analysis and insights",
//   "business plan development",
//   "infographic animation",
//   "youtube thumbnails",
//   "landing page copywriting",
//   "social media audit",
//   "web hosting setup",
//   "video game sound design",
//   "user experience (ux) testing",
//   "article editing",
//   "ui animation",
//   "shopify theme customization",
//   "email newsletter campaigns",
//   "business logo design",
//   "game level design",
//   "seo strategy",
//   "magazine design",
//   "speech coaching",
//   "api documentation",
//   "website maintenance",
//   "book cover illustration",
//   "social media advertising campaigns",
//   "app localization",
//   "market trend analysis",
//   "brochure design",
//   "linkedin profile optimization",
//   "3d animation",
//   "business proposal writing",
//   "podcast production",
//   "chatbot development",
//   "presentation slide design",
//   "social media influencer collaboration",
//   "app security testing",
//   "infographic design",
//   "seo content creation",
//   "data entry and cleanup",
//   "business card design",
//   "virtual event production",
// ];

export type TagOption = {
  label: string;
  value: string;
};

export const tagOptions: TagOption[] = [
  { label: "web development", value: "web development" },
  { label: "graphic design", value: "graphic design" },
  { label: "content writing", value: "content writing" },
  { label: "mobile app development", value: "mobile app development" },
  { label: "ui/ux design", value: "ui/ux design" },
  { label: "seo optimization", value: "seo optimization" },
  { label: "social media management", value: "social media management" },
  { label: "video editing", value: "video editing" },
  { label: "illustration", value: "illustration" },
  { label: "data entry", value: "data entry" },
  { label: "e-commerce development", value: "e-commerce development" },
  { label: "copywriting", value: "copywriting" },
  { label: "logo design", value: "logo design" },
  { label: "blogging", value: "blogging" },
  { label: "wordpress development", value: "wordpress development" },
  { label: "animation", value: "animation" },
  { label: "virtual assistance", value: "virtual assistance" },
  { label: "digital marketing", value: "digital marketing" },
  { label: "voiceover", value: "voiceover" },
  { label: "email marketing", value: "email marketing" },
  { label: "photography", value: "photography" },
  { label: "transcription", value: "transcription" },
  { label: "app store optimization", value: "app store optimization" },
  { label: "proofreading", value: "proofreading" },
  { label: "game development", value: "game development" },
  { label: "infographic design", value: "infographic design" },
  { label: "social media advertising", value: "social media advertising" },
  { label: "shopify development", value: "shopify development" },
  { label: "bookkeeping", value: "bookkeeping" },
  { label: "podcast editing", value: "podcast editing" },
  { label: "whiteboard animation", value: "whiteboard animation" },
  { label: "3d modeling", value: "3d modeling" },
  { label: "presentation design", value: "presentation design" },
  { label: "e-book writing", value: "e-book writing" },
  { label: "data analysis", value: "data analysis" },
  { label: "branding", value: "branding" },
  { label: "resume writing", value: "resume writing" },
  { label: "influencer marketing", value: "influencer marketing" },
  { label: "product photography", value: "product photography" },
  { label: "landing page design", value: "landing page design" },
  { label: "market research", value: "market research" },
  { label: "voice acting", value: "voice acting" },
  { label: "motion graphics", value: "motion graphics" },
  { label: "wordpress customization", value: "wordpress customization" },
  { label: "content strategy", value: "content strategy" },
  { label: "social media consulting", value: "social media consulting" },
  { label: "logo animation", value: "logo animation" },
  { label: "data mining", value: "data mining" },
  { label: "android app development", value: "android app development" },
  { label: "web scraping", value: "web scraping" },
  { label: "affiliate marketing", value: "affiliate marketing" },
  { label: "app ui design", value: "app ui design" },
  { label: "video production", value: "video production" },
  { label: "article writing", value: "article writing" },
  { label: "seo audit", value: "seo audit" },
  { label: "character design", value: "character design" },
  { label: "virtual events management", value: "virtual events management" },
  { label: "social media graphics", value: "social media graphics" },
  { label: "shopify setup", value: "shopify setup" },
  { label: "financial planning", value: "financial planning" },
  { label: "podcast scriptwriting", value: "podcast scriptwriting" },
  { label: "explainer videos", value: "explainer videos" },
  { label: "architectural rendering", value: "architectural rendering" },
  { label: "newsletter design", value: "newsletter design" },
  { label: "ghostwriting", value: "ghostwriting" },
  { label: "social media marketing", value: "social media marketing" },
  {
    label: "app store review management",
    value: "app store review management",
  },
  { label: "book cover design", value: "book cover design" },
  {
    label: "voice assistant development",
    value: "voice assistant development",
  },
  { label: "market analysis", value: "market analysis" },
  { label: "scriptwriting", value: "scriptwriting" },
  { label: "influencer outreach", value: "influencer outreach" },
  { label: "data visualization", value: "data visualization" },
  { label: "website optimization", value: "website optimization" },
  { label: "facebook ads", value: "facebook ads" },
  { label: "portrait photography", value: "portrait photography" },
  { label: "animation scriptwriting", value: "animation scriptwriting" },
  { label: "wordpress troubleshooting", value: "wordpress troubleshooting" },
  { label: "business card design", value: "business card design" },
  {
    label: "social media content creation",
    value: "social media content creation",
  },
  { label: "logo redesign", value: "logo redesign" },
  { label: "market trend analysis", value: "market trend analysis" },
  {
    label: "proof of concept (poc) development",
    value: "proof of concept (poc) development",
  },
  { label: "seo copywriting", value: "seo copywriting" },
  { label: "motion design", value: "motion design" },
  { label: "product design", value: "product design" },
  { label: "catalog design", value: "catalog design" },
  { label: "financial modeling", value: "financial modeling" },
  { label: "podcast hosting", value: "podcast hosting" },
  {
    label: "explainer video scriptwriting",
    value: "explainer video scriptwriting",
  },
  { label: "cad design", value: "cad design" },
  { label: "brochure design", value: "brochure design" },
  { label: "business plan writing", value: "business plan writing" },
  {
    label: "social media growth strategy",
    value: "social media growth strategy",
  },
  { label: "wordpress migration", value: "wordpress migration" },
  {
    label: "affiliate program management",
    value: "affiliate program management",
  },
  { label: "user flow design", value: "user flow design" },
  { label: "videography", value: "videography" },
  { label: "data entry and analysis", value: "data entry and analysis" },
  { label: "app design", value: "app design" },
  { label: "business writing", value: "business writing" },
  { label: "front-end development", value: "front-end development" },
  { label: "video scriptwriting", value: "video scriptwriting" },
  { label: "social media strategy", value: "social media strategy" },
  { label: "mobile game development", value: "mobile game development" },
  { label: "creative writing", value: "creative writing" },
  { label: "app marketing", value: "app marketing" },
  { label: "digital illustration", value: "digital illustration" },
  { label: "user interface (ui) design", value: "user interface (ui) design" },
  { label: "technical writing", value: "technical writing" },
  { label: "backend development", value: "backend development" },
  { label: "poster design", value: "poster design" },
  { label: "ebook formatting", value: "ebook formatting" },
  { label: "motion graphics animation", value: "motion graphics animation" },
  { label: "google ads campaigns", value: "google ads campaigns" },
  { label: "book editing", value: "book editing" },
  { label: "podcast cover design", value: "podcast cover design" },
  {
    label: "app store optimization (aso)",
    value: "app store optimization (aso)",
  },
  { label: "software testing", value: "software testing" },
  { label: "package design", value: "package design" },
  { label: "resume design", value: "resume design" },
  { label: "sound editing", value: "sound editing" },
  { label: "email template design", value: "email template design" },
  { label: "data cleaning", value: "data cleaning" },
  { label: "facebook marketing", value: "facebook marketing" },
  { label: "product rendering", value: "product rendering" },
  { label: "business consulting", value: "business consulting" },
  { label: "e-commerce management", value: "e-commerce management" },
  { label: "book illustration", value: "book illustration" },
  { label: "social media analytics", value: "social media analytics" },
  { label: "android app ui design", value: "android app ui design" },
  { label: "speech writing", value: "speech writing" },
  { label: "api integration", value: "api integration" },
  { label: "event photography", value: "event photography" },
  { label: "landing page optimization", value: "landing page optimization" },
  { label: "press release writing", value: "press release writing" },
  { label: "video editing training", value: "video editing training" },
  { label: "ui/ux consultation", value: "ui/ux consultation" },
  { label: "ios app development", value: "ios app development" },
  { label: "book formatting", value: "book formatting" },
  { label: "explainer video production", value: "explainer video production" },
  { label: "youtube seo", value: "youtube seo" },
  { label: "financial analysis", value: "financial analysis" },
  {
    label: "virtual reality (vr) development",
    value: "virtual reality (vr) development",
  },
  { label: "voice over scriptwriting", value: "voice over scriptwriting" },
  { label: "plugin development", value: "plugin development" },
  {
    label: "social media management training",
    value: "social media management training",
  },
  { label: "app prototyping", value: "app prototyping" },
  {
    label: "market research report writing",
    value: "market research report writing",
  },
  { label: "blog management", value: "blog management" },
  { label: "online course creation", value: "online course creation" },
  { label: "motion graphics design", value: "motion graphics design" },
  { label: "youtube channel growth", value: "youtube channel growth" },
  {
    label: "wordpress theme customization",
    value: "wordpress theme customization",
  },
  { label: "data analysis and insights", value: "data analysis and insights" },
  { label: "business plan development", value: "business plan development" },
  { label: "infographic animation", value: "infographic animation" },
  { label: "youtube thumbnails", value: "youtube thumbnails" },
  { label: "landing page copywriting", value: "landing page copywriting" },
  { label: "social media audit", value: "social media audit" },
  { label: "web hosting setup", value: "web hosting setup" },
  { label: "video game sound design", value: "video game sound design" },
  {
    label: "user experience (ux) testing",
    value: "user experience (ux) testing",
  },
  { label: "article editing", value: "article editing" },
  { label: "ui animation", value: "ui animation" },
  {
    label: "shopify theme customization",
    value: "shopify theme customization",
  },
  { label: "email newsletter campaigns", value: "email newsletter campaigns" },
  { label: "business logo design", value: "business logo design" },
  { label: "game level design", value: "game level design" },
  { label: "seo strategy", value: "seo strategy" },
  { label: "magazine design", value: "magazine design" },
  { label: "speech coaching", value: "speech coaching" },
  { label: "api documentation", value: "api documentation" },
  { label: "website maintenance", value: "website maintenance" },
  { label: "book cover illustration", value: "book cover illustration" },
  {
    label: "social media advertising campaigns",
    value: "social media advertising campaigns",
  },
  { label: "app localization", value: "app localization" },
  {
    label: "linkedin profile optimization",
    value: "linkedin profile optimization",
  },
  { label: "3d animation", value: "3d animation" },
  { label: "business proposal writing", value: "business proposal writing" },
  { label: "podcast production", value: "podcast production" },
  { label: "chatbot development", value: "chatbot development" },
  { label: "presentation slide design", value: "presentation slide design" },
  {
    label: "social media influencer collaboration",
    value: "social media influencer collaboration",
  },
  { label: "app security testing", value: "app security testing" },
  { label: "seo content creation", value: "seo content creation" },
  { label: "data entry and cleanup", value: "data entry and cleanup" },
  { label: "virtual event production", value: "virtual event production" },
];
