export const FETCH_ALL_CLIENTS_LIST = "FETCH_ALL_CLIENTS_LIST";
export const FETCH_ALL_CLIENTS_DETAILS = "FETCH_ALL_CLIENTS_DETAILS";
export const FETCH_ALL_CLIENTS_LAST_MESSAGE = "FETCH_ALL_CLIENTS_LAST_MESSAGE";

export const UPDATE_ALL_CLIENTS_LIST = "UPDATE_ALL_CLIENTS_LIST";
export const UPDATE_CLIENT_LAST_MESSAGE = "UPDATE_CLIENT_LAST_MESSAGE";
export const UPDATE_CLIENT_DETAILS = "UPDATE_CLIENT_DETAILS";

export const FETCH_ALL_CHATS_WITH_CLIENT = "FETCH_ALL_CHATS_WITH_CLIENT";
export const UPDATE_ALL_CHATS_WITH_CLIENT = "UPDATE_ALL_CHATS_WITH_CLIENT";

export const FETCH_ONLINE_STATUS_OF_CLIENTS = "FETCH_ONLINE_STATUS_OF_CLIENTS";
export const UPDATE_ONLINE_STATUS_OF_CLIENTS =
  "UPDATE_ONLINE_STATUS_OF_CLIENTS";
